version: "3.8"

volumes:
  config:

services:
  qbittorrent:
    image: linuxserver/qbittorrent:arm64v8-latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8001
    volumes:
      - config:/config
      - /media/devmon/sda1-usb-TOSHIBA_MQ01ABF0/Torrent:/downloads
    ports:
      - 8001:8001
      - 6881:6881
      - 6881:6881/udp
