services:
  home-assistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:latest"
    restart: unless-stopped
    volumes:
      - ./data/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0
    privileged: true
    network_mode: host

  portainer:
    image: portainer/portainer:linux-arm64-2.0.1
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    volumes:
      - ./data/jellyfin/config:/config
      - /home/orangepi/Downloads/Torrent/Movies:/data/movies
      - /home/orangepi/Downloads/Torrent/TV:/data/tv
      - /home/orangepi/Downloads/Torrent/Music:/data/music
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8000:8096

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    volumes:
      - ./data/prowlarr/config:/config
    ports:
      - 9696:9696

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    volumes:
      - ./data/radarr/config:/config
      - /home/orangepi/Downloads/Torrent/Movies:/movies
      - /home/orangepi/Downloads/Torrent/Downloaded:/downloads/Downloaded
    ports:
      - 7878:7878

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    volumes:
      - ./data/sonarr/config:/config
      - /home/orangepi/Downloads/Torrent/TV:/tv
      - /home/orangepi/Downloads/Torrent/Downloaded:/downloads/Downloaded
    ports:
      - 8989:8989

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    volumes:
      - ./data/lidarr/config:/config
      - /home/orangepi/Downloads/Torrent/Music:/music
      - /home/orangepi/Downloads/Torrent/Downloaded:/downloads/Downloaded
    ports:
      - 8686:8686

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LOG_HTML: ${LOG_HTML:-false}
      CAPTCHA_SOLVER: ${CAPTCHA_SOLVER:-none}
      TZ: Europe/London
    ports:
      - "${PORT:-8191}:8191"

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      WEBUI_PORT: 8001
    volumes:
      - ./data/qbittorrent/config:/config
      - /home/orangepi/Downloads/Torrent:/downloads
    ports:
      - 8001:8001
      - 6881:6881
      - 6881:6881/udp

  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    networks:
      dns-network:
        ipv4_address: 172.20.0.200
    volumes:
      - ./data/adguardhome/workdir:/opt/adguardhome/work
      - ./data/adguardhome/confdir:/opt/adguardhome/conf
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 443:443/tcp
      - 443:443/udp
      - 3000:3000/tcp

  unbound:
    container_name: unbound
    image: madnuttah/unbound:latest
    hostname: unbound
    ports:
      - 5335:5335/tcp
      - 5335:5335/udp
    networks:
      dns-network:
        ipv4_address: 172.20.0.253
    environment:
      TZ: Etc/UTC
      UNBOUND_UID: 1000
      UNBOUND_GID: 1000
      HEALTHCHECK_PORT: 5335
      EXTENDED_HEALTHCHECK: "true"
      ENABLE_STATS: "true"
    restart: unless-stopped
    healthcheck:
      test: /usr/local/unbound/sbin/healthcheck.sh
      interval: 60s
      retries: 5
      start_period: 15s
      timeout: 30s

networks:
  dns-network:
    driver: bridge
    driver_opts:
      parent: wlan0
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
