---
#--------------------------------------------------------------------#
#                          Home Automation                           #
#--------------------------------------------------------------------#
services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant
    env_file: .env
    restart: unless-stopped
    dns:
      - 172.16.0.201
    networks:
      - home-assistant-network
      - dns-network
    volumes:
      - ./config/home-assistant/configuration.yaml:/config/configuration.yaml
      - ./data/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    ports:
      - 8123:8123

  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: mqtt
    env_file: .env
    networks:
      - home-assistant-network
    restart: unless-stopped
    volumes:
      - "./data/mosquitto/data:/mosquitto"
    expose:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    env_file: .env
    networks:
      - home-assistant-network
    restart: unless-stopped
    volumes:
      - ./config/zigbee2mqtt/configuration.yaml:/app/data/configuration.yaml
      - ./data/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    devices:
      - /dev/serial/by-id/usb-SMLIGHT_SMLIGHT_SLZB-06_58a6a4c52e72ef11a0c846848fcc3fa0-if00-port0:/dev/ttyUSB0

networks:
  home-assistant-network:
    driver: bridge

---
#--------------------------------------------------------------------#
#                          Media Streaming                           #
#--------------------------------------------------------------------#
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    env_file: .env
    dns:
      - 172.16.0.201
    networks:
      - media-network
      - dns-network
    restart: unless-stopped
    volumes:
      - ./data/jellyfin/config:/config
      - /home/s1n7ax/Downloads/Torrent/Movies:/data/movies
      - /home/s1n7ax/Downloads/Torrent/TV:/data/tv
      - /home/s1n7ax/Downloads/Torrent/Music:/data/music
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8000:8096

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    env_file: .env
    dns:
      - 172.16.0.201
    networks:
      - media-network
      - dns-network
    restart: unless-stopped
    volumes:
      - ./data/prowlarr/config:/config
    ports:
      - 9696:9696

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file: .env
    restart: unless-stopped
    dns:
      - 172.16.0.201
    networks:
      - media-network
      - dns-network
      - home-assistant-network
    volumes:
      - ./data/radarr/config:/config
      - /home/s1n7ax/Downloads/Torrent/Movies:/movies
      - /home/s1n7ax/Downloads/Torrent/Downloaded:/downloads/Downloaded
    ports:
      - 7878:7878

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file: .env
    dns:
      - 172.16.0.201
    networks:
      - media-network
      - dns-network
    restart: unless-stopped
    volumes:
      - ./data/sonarr/config:/config
      - /home/s1n7ax/Downloads/Torrent/TV:/tv
      - /home/s1n7ax/Downloads/Torrent/Downloaded:/downloads/Downloaded
    ports:
      - 8989:8989

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    env_file: .env
    dns:
      - 172.16.0.201
    networks:
      - media-network
      - dns-network
    restart: unless-stopped
    volumes:
      - ./data/lidarr/config:/config
      - /home/s1n7ax/Downloads/Torrent/Music:/music
      - /home/s1n7ax/Downloads/Torrent/Downloaded:/downloads/Downloaded
    ports:
      - 8686:8686

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    env_file: .env
    dns:
      - 172.16.0.201
    networks:
      - media-network
      - dns-network
    restart: unless-stopped
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LOG_HTML: ${LOG_HTML:-false}
      CAPTCHA_SOLVER: ${CAPTCHA_SOLVER:-none}
      TZ: Europe/London
    ports:
      - 8191:8191

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    env_file: .env
    dns:
      - 172.16.0.201
    networks:
      - media-network
      - dns-network
      - home-assistant-network
    restart: unless-stopped
    environment:
      WEBUI_PORT: 8001
    volumes:
      - ./data/qbittorrent/config:/config
      - /home/s1n7ax/Downloads/Torrent:/downloads
    ports:
      - 8001:8001
      - 6881:6881
      - 6881:6881/udp
networks:
  media-network:
    driver: bridge

---
#--------------------------------------------------------------------#
#                             DNS Server                             #
#--------------------------------------------------------------------#
services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    env_file: .env
    restart: unless-stopped
    networks:
      dns-network:
        ipv4_address: 172.16.0.201
    volumes:
      - ./data/adguardhome/workdir:/opt/adguardhome/work
      - ./data/adguardhome/confdir:/opt/adguardhome/conf
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 443:443/tcp
      - 443:443/udp
      - 3000:3000/tcp

  unbound:
    build:
      context: ./docker/unbound
    container_name: unbound
    env_file: .env
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      dns-network:
        ipv4_address: 172.16.0.200
    cap_add:
      - NET_ADMIN
    expose:
      - 53/tcp
      - 53/udp
      - "80"
      - "443"
    volumes:
      - ./config/unbound/unbound.conf:/etc/unbound/unbound.conf

networks:
  dns-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1

---
#--------------------------------------------------------------------#
#                             Monitoring                             #
#--------------------------------------------------------------------#
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "${UID:-1000}:${GID:-1000}"
    env_file: .env
    ports:
      - 3001:3000
    volumes:
      - ./data/grafana/config:/var/lib/grafana
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "${UID:-1000}:${GID:-1000}"
    env_file: .env
    command: "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./data/prometheus/data:/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    depends_on:
      - node-exporter
      - cadvisor

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    env_file: .env
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    expose:
      - 9100

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    env_file: .env
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg

---
# --------------------------------------------------------------------#
#                        Container Management                        #
# --------------------------------------------------------------------#
services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    env_file: .env
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer/data:/data

---
#--------------------------------------------------------------------#
#                               Tunnel                               #
#--------------------------------------------------------------------#
services:
  wireguard:
    build: ./docker/wireguard
    container_name: wireguard
    env_file: .env
    dns:
      - 172.16.0.201
    networks:
      - dns-network
      - wireguard-network
      - home-assistant-network
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    volumes:
      - ./data/wireguard:/etc/wireguard
      - ./config/wireguard/nginx.conf:/etc/nginx/nginx.conf
      - ./config/wireguard/html:/var/www/html
    ports:
      - 80:80
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
networks:
  wireguard-network:
    driver: bridge
