version: "3.8"

volumes:
  nextcloud:
  db:

services:
  db:
    image: postgres:12.16
    container_name: postgres_for_nextcloud
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  adminer:
    image: adminer:4.8.1
    container_name: adminer_for_nextcloud
    restart: unless-stopped
    ports:
      - 81:8080

  app:
    image: nextcloud:stable
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
