version: "3.8"

volumes:
  config:

services:
  backup:
    image: alpine:latest
    container_name: firefox-backup
    volumes:
      - ./backup:/backup
      - config:/config
      - /media/orangepi/torrent-drive/Torrent/Movies:/data/movies
      - /media/orangepi/torrent-drive/Torrent/TV:/data/tvshows

    command: sh -c '
      apk add xz;

      XZ_OPT=-9 tar -vJcf /backup/config.tar.xz -C /config ./;
      XZ_OPT=-9 tar -vJcf /backup/movies.tar.xz -C /data/movies ./;
      XZ_OPT=-9 tar -vJcf /backup/tvshows.tar.xz -C /data/tvshows ./;
      '

  restore:
    image: busybox:latest
    container_name: firefox-restore
    volumes:
      - ./backup:/backup
      - config:/config
      - /media/orangepi/torrent-drive/Torrent/Movies:/data/movies
      - /media/orangepi/torrent-drive/Torrent/TV:/data/tvshows
    command: sh -c '
      rm -rf /config/* /config/.[!.]*;

      tar -C /config -vxJf /backup/config.tar.xz
      tar -C /data/movies -vxJf /backup/movies.tar.xz
      tar -C /data/tvshows -vxJf /backup/tvshows.tar.xz
      '
