version: "3.8"

volumes:
  config:

services:
  jellyfin:
    image: linuxserver/jellyfin:arm64v8-latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - config:/config
      - /media/devmon/sda1-usb-WDC_WD10_JPVT-75/Torrent/Movies:/data/movies
      - /media/devmon/sda1-usb-WDC_WD10_JPVT-75/Torrent/TV:/data/tvshows
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8000:8096
