version: "3.8"

volumes:
  config:

services:
  backup:
    image: alpine:latest
    container_name: firefox-backup
    volumes:
      - ./backup:/backup
      - config:/config
    command: /bin/sh -c "apk add xz ; XZ_OPT=-9 tar -vJcf /backup/config.tar.xz -C /config ./"

  restore:
    image: busybox:latest
    container_name: firefox-restore
    volumes:
      - ./backup:/backup
      - config:/config
    command: sh -c "rm -rf /config/* /config/.[!.]* ; tar -C /config -vxJf /backup/config.tar.xz"
