version: "3.8"

volumes:
  config:

services:
  firefox:
    image: linuxserver/firefox:arm64v8-latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - config:/config
      - /home/orangepi/downloads:/downloads
    ports:
      - 3001:3000
      - 3002:3001
    shm_size: "1gb"
    restart: unless-stopped
