version: "3.8"
services:
  portainer:
    image: portainer/portainer:linux-arm64-2.0.1
    container_name: portainer
    restart: unless-stopped
    expose:
      - 8000
      - 9000
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
