homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8080
advanced:
  pan_id: 6757
  ext_pan_id:
    - 221
    - 221
    - 221
    - 221
    - 221
    - 221
    - 221
    - 221
  channel: 11
  network_key: '!secret.yaml network_key'
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
availability:
  active:
    timeout: 5
  passive:
    timeout: 1500
devices:
  '0x70b3d52b600a5ec6':
    friendly_name: p computer
  '0xa4c1386bd71e3654':
    friendly_name: p ac
  '0xa4c138971e946b01':
    friendly_name: b office srinesh's desk
  '0xa4c1384a42188985':
    friendly_name: b office nidu's desk
  '0x70b3d52b600ba845':
    friendly_name: '0x70b3d52b600ba845'
  '0x70b3d52b600a5ec7':
    friendly_name: p water pump
