homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8080
advanced:
  pan_id: 6755
  ext_pan_id:
    - 221
    - 221
    - 221
    - 221
    - 221
    - 221
    - 221
    - 221
  channel: 11
  network_key:
    - 69
    - 53
    - 230
    - 32
    - 67
    - 176
    - 39
    - 220
    - 32
    - 132
    - 83
    - 129
    - 153
    - 16
    - 93
    - 155
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0x70b3d52b600ba845':
    friendly_name: p test
availability:
  active:
    timeout: 5
  passive:
    timeout: 1500
